### ISSUE TITLE
Electrolyte function - hard coded values

### ISSUE THREAD

**Issue by environmat** [mjlacey/cellmodels#2]
Hi there, me again: 

I am trying to wrap my head around the electrolyte function. Can someone help me figure out the hard coded values, what is the origin? 

1.1299 is the EC:DEC density (g/cm3), but what are the 0.1222 and the 0.7641 doing? 

` function Electrolyte(salt, solvent, concentration, density, saltmassfrac)
        if salt == "LiPF6" && concentration != nothing
            saltmassfrac = 0.1222 * concentration
            if density == nothing && solvent == "EC:DEC"
                density = 0.7641 * saltmassfrac + 1.1299
            end
        end
        new(salt, solvent, concentration, density, saltmassfrac)
    end
`

Thanks in advance. 
Best
Matthias

**Comment by mjlacey** [comment]
Hi Matthias,

Sorry for the late reply. This was something empirical I put in for my own use before I decided to share the code on Github. It comes from a paper which had data on the density etc of LiPF6 in EC:DEC electrolytes and it is basically the coefficients for a linear fit of the mass fraction of the salt in the electrolyte and the electrolyte density as a function of concentration, which is valid in the usual range. So the 0.1222 for example basically just says that the mass of the salt is 12.22% at 1 M and then that mass fraction goes into the density equation.

To be honest it should probably be removed/rewritten so that stuff like this is not coded into the definition of the `Electrolyte` class but is in a separate material database or something where a function generates a specific `Electrolyte` object based on some material properties.

**Comment by environmat** [comment]
Hey  @mjlacey, 
thanks for that explanation. Makes sense. I will look into that. 
Best
Matthias
